networks:
  default: localnet
  localnet:
    url: "http://127.0.0.1:4000/api"
  studio_devnet:
    url: "https://studio-dev.genlayer.com/api"
  studionet: {}

paths:
  contracts: "contracts"

environment: .env